# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: event.proto

import sys
_b=sys.version_info[0]<3 and (lambda x:x) or (lambda x:x.encode('latin1'))
from google.protobuf import descriptor as _descriptor
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor.FileDescriptor(
  name='event.proto',
  package='CMD',
  syntax='proto3',
  serialized_options=None,
  serialized_pb=_b('\n\x0b\x65vent.proto\x12\x03\x43MD\"\x1d\n\tevntParam\x12\x10\n\x08priority\x18\x01 \x01(\x04\"?\n\x08\x65vntData\x12\x0f\n\x07\x63lassID\x18\x01 \x01(\x04\x12\x0f\n\x07\x65vnetID\x18\x02 \x01(\x04\x12\x11\n\ttimestamp\x18\x03 \x01(\tb\x06proto3')
)




_EVNTPARAM = _descriptor.Descriptor(
  name='evntParam',
  full_name='CMD.evntParam',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='priority', full_name='CMD.evntParam.priority', index=0,
      number=1, type=4, cpp_type=4, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=20,
  serialized_end=49,
)


_EVNTDATA = _descriptor.Descriptor(
  name='evntData',
  full_name='CMD.evntData',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='classID', full_name='CMD.evntData.classID', index=0,
      number=1, type=4, cpp_type=4, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='evnetID', full_name='CMD.evntData.evnetID', index=1,
      number=2, type=4, cpp_type=4, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='timestamp', full_name='CMD.evntData.timestamp', index=2,
      number=3, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=51,
  serialized_end=114,
)

DESCRIPTOR.message_types_by_name['evntParam'] = _EVNTPARAM
DESCRIPTOR.message_types_by_name['evntData'] = _EVNTDATA
_sym_db.RegisterFileDescriptor(DESCRIPTOR)

evntParam = _reflection.GeneratedProtocolMessageType('evntParam', (_message.Message,), dict(
  DESCRIPTOR = _EVNTPARAM,
  __module__ = 'event_pb2'
  # @@protoc_insertion_point(class_scope:CMD.evntParam)
  ))
_sym_db.RegisterMessage(evntParam)

evntData = _reflection.GeneratedProtocolMessageType('evntData', (_message.Message,), dict(
  DESCRIPTOR = _EVNTDATA,
  __module__ = 'event_pb2'
  # @@protoc_insertion_point(class_scope:CMD.evntData)
  ))
_sym_db.RegisterMessage(evntData)


# @@protoc_insertion_point(module_scope)
