# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: messageparam.proto

import sys
_b=sys.version_info[0]<3 and (lambda x:x) or (lambda x:x.encode('latin1'))
from google.protobuf import descriptor as _descriptor
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor.FileDescriptor(
  name='messageparam.proto',
  package='CMD',
  syntax='proto3',
  serialized_options=None,
  serialized_pb=_b('\n\x12messageparam.proto\x12\x03\x43MD\"m\n\rmessageParams\x12\x10\n\x08\x63lientID\x18\x01 \x01(\x04\x12\x15\n\rtransactionID\x18\x02 \x01(\x04\x12\x11\n\tsessionID\x18\x03 \x01(\x04\x12\x0e\n\x06status\x18\x04 \x01(\t\x12\x10\n\x08priority\x18\x05 \x01(\rb\x06proto3')
)




_MESSAGEPARAMS = _descriptor.Descriptor(
  name='messageParams',
  full_name='CMD.messageParams',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='clientID', full_name='CMD.messageParams.clientID', index=0,
      number=1, type=4, cpp_type=4, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='transactionID', full_name='CMD.messageParams.transactionID', index=1,
      number=2, type=4, cpp_type=4, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='sessionID', full_name='CMD.messageParams.sessionID', index=2,
      number=3, type=4, cpp_type=4, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='status', full_name='CMD.messageParams.status', index=3,
      number=4, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='priority', full_name='CMD.messageParams.priority', index=4,
      number=5, type=13, cpp_type=3, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=27,
  serialized_end=136,
)

DESCRIPTOR.message_types_by_name['messageParams'] = _MESSAGEPARAMS
_sym_db.RegisterFileDescriptor(DESCRIPTOR)

messageParams = _reflection.GeneratedProtocolMessageType('messageParams', (_message.Message,), dict(
  DESCRIPTOR = _MESSAGEPARAMS,
  __module__ = 'messageparam_pb2'
  # @@protoc_insertion_point(class_scope:CMD.messageParams)
  ))
_sym_db.RegisterMessage(messageParams)


# @@protoc_insertion_point(module_scope)
