# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: scCPD.proto

import sys
_b=sys.version_info[0]<3 and (lambda x:x) or (lambda x:x.encode('latin1'))
from google.protobuf import descriptor as _descriptor
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor.FileDescriptor(
  name='scCPD.proto',
  package='CMD',
  syntax='proto3',
  serialized_options=None,
  serialized_pb=_b('\n\x0bscCPD.proto\x12\x03\x43MD\"\xa4\x01\n\x10\x61\x64\x64SmartContract\x12\x14\n\x0c\x63ontractName\x18\x01 \x01(\t\x12\x18\n\x10\x63ontractFileName\x18\x02 \x01(\t\x12\x10\n\x08\x66ileType\x18\x03 \x01(\t\x12\x0f\n\x07\x66ileMap\x18\x04 \x01(\t\x12\x13\n\x0b\x66ileContent\x18\x05 \x01(\t\x12\x15\n\raccessControl\x18\x06 \x01(\t\x12\x11\n\ttimestamp\x18\x07 \x01(\t\")\n\x11readSmartContract\x12\x14\n\x0c\x63ontractName\x18\x01 \x01(\tb\x06proto3')
)




_ADDSMARTCONTRACT = _descriptor.Descriptor(
  name='addSmartContract',
  full_name='CMD.addSmartContract',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='contractName', full_name='CMD.addSmartContract.contractName', index=0,
      number=1, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='contractFileName', full_name='CMD.addSmartContract.contractFileName', index=1,
      number=2, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='fileType', full_name='CMD.addSmartContract.fileType', index=2,
      number=3, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='fileMap', full_name='CMD.addSmartContract.fileMap', index=3,
      number=4, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='fileContent', full_name='CMD.addSmartContract.fileContent', index=4,
      number=5, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='accessControl', full_name='CMD.addSmartContract.accessControl', index=5,
      number=6, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='timestamp', full_name='CMD.addSmartContract.timestamp', index=6,
      number=7, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=21,
  serialized_end=185,
)


_READSMARTCONTRACT = _descriptor.Descriptor(
  name='readSmartContract',
  full_name='CMD.readSmartContract',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='contractName', full_name='CMD.readSmartContract.contractName', index=0,
      number=1, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=187,
  serialized_end=228,
)

DESCRIPTOR.message_types_by_name['addSmartContract'] = _ADDSMARTCONTRACT
DESCRIPTOR.message_types_by_name['readSmartContract'] = _READSMARTCONTRACT
_sym_db.RegisterFileDescriptor(DESCRIPTOR)

addSmartContract = _reflection.GeneratedProtocolMessageType('addSmartContract', (_message.Message,), dict(
  DESCRIPTOR = _ADDSMARTCONTRACT,
  __module__ = 'scCPD_pb2'
  # @@protoc_insertion_point(class_scope:CMD.addSmartContract)
  ))
_sym_db.RegisterMessage(addSmartContract)

readSmartContract = _reflection.GeneratedProtocolMessageType('readSmartContract', (_message.Message,), dict(
  DESCRIPTOR = _READSMARTCONTRACT,
  __module__ = 'scCPD_pb2'
  # @@protoc_insertion_point(class_scope:CMD.readSmartContract)
  ))
_sym_db.RegisterMessage(readSmartContract)


# @@protoc_insertion_point(module_scope)
