# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: tknCPD.proto

import sys
_b=sys.version_info[0]<3 and (lambda x:x) or (lambda x:x.encode('latin1'))
from google.protobuf import descriptor as _descriptor
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor.FileDescriptor(
  name='tknCPD.proto',
  package='CMD',
  syntax='proto3',
  serialized_options=None,
  serialized_pb=_b('\n\x0ctknCPD.proto\x12\x03\x43MD\"b\n\x0b\x63reateToken\x12\x11\n\ttokenName\x18\x01 \x01(\t\x12\x0e\n\x06symbol\x18\x02 \x01(\t\x12\r\n\x05value\x18\x03 \x01(\x02\x12\x0e\n\x06supply\x18\x04 \x01(\x02\x12\x11\n\ttimestamp\x18\x05 \x01(\t\"B\n\ngrantToken\x12\x11\n\ttokenName\x18\x01 \x01(\t\x12\x0e\n\x06supply\x18\x02 \x01(\x02\x12\x11\n\ttimestamp\x18\x03 \x01(\t\"r\n\x11modifyClientToken\x12\x10\n\x08\x63lientID\x18\x01 \x01(\x04\x12\x11\n\ttokenName\x18\x02 \x01(\t\x12\x0e\n\x06\x61mount\x18\x03 \x01(\x02\x12\x11\n\ttimestamp\x18\x04 \x01(\t\x12\x15\n\rtransactionID\x18\x05 \x01(\x04\"3\n\x0c\x63heckBalance\x12\x10\n\x08\x63lientID\x18\x01 \x01(\x04\x12\x11\n\ttokenName\x18\x02 \x01(\t\"E\n\x0e\x63heckAllowance\x12\x10\n\x08\x63lientID\x18\x01 \x01(\x04\x12\x11\n\ttokenName\x18\x02 \x01(\t\x12\x0e\n\x06\x61mount\x18\x03 \x01(\x02\"{\n\x0bmakeRequest\x12\x10\n\x08\x63lientID\x18\x01 \x01(\x04\x12\x11\n\ttokenName\x18\x02 \x01(\t\x12\x0e\n\x06\x61mount\x18\x03 \x01(\x02\x12\x11\n\ttimestamp\x18\x04 \x01(\t\x12\x11\n\trequestID\x18\x05 \x01(\x04\x12\x11\n\tsessionID\x18\x06 \x01(\x04\"\x8a\x01\n\x0e\x61pproveRequest\x12\x11\n\trequestID\x18\x01 \x01(\x04\x12\x15\n\rapproveStatus\x18\x02 \x01(\x08\x12\x11\n\ttokenName\x18\x03 \x01(\t\x12\x11\n\ttimestamp\x18\x04 \x01(\t\x12\x15\n\rtransactionID\x18\x05 \x01(\x04\x12\x11\n\tsessionID\x18\x06 \x01(\x04\"i\n\x08transfer\x12\x10\n\x08\x63lientID\x18\x01 \x01(\x04\x12\x11\n\ttokenName\x18\x02 \x01(\t\x12\x0e\n\x06\x61mount\x18\x03 \x01(\x02\x12\x11\n\ttimestamp\x18\x04 \x01(\t\x12\x15\n\rtransactionID\x18\x05 \x01(\x04\x62\x06proto3')
)




_CREATETOKEN = _descriptor.Descriptor(
  name='createToken',
  full_name='CMD.createToken',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='tokenName', full_name='CMD.createToken.tokenName', index=0,
      number=1, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='symbol', full_name='CMD.createToken.symbol', index=1,
      number=2, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='value', full_name='CMD.createToken.value', index=2,
      number=3, type=2, cpp_type=6, label=1,
      has_default_value=False, default_value=float(0),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='supply', full_name='CMD.createToken.supply', index=3,
      number=4, type=2, cpp_type=6, label=1,
      has_default_value=False, default_value=float(0),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='timestamp', full_name='CMD.createToken.timestamp', index=4,
      number=5, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=21,
  serialized_end=119,
)


_GRANTTOKEN = _descriptor.Descriptor(
  name='grantToken',
  full_name='CMD.grantToken',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='tokenName', full_name='CMD.grantToken.tokenName', index=0,
      number=1, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='supply', full_name='CMD.grantToken.supply', index=1,
      number=2, type=2, cpp_type=6, label=1,
      has_default_value=False, default_value=float(0),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='timestamp', full_name='CMD.grantToken.timestamp', index=2,
      number=3, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=121,
  serialized_end=187,
)


_MODIFYCLIENTTOKEN = _descriptor.Descriptor(
  name='modifyClientToken',
  full_name='CMD.modifyClientToken',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='clientID', full_name='CMD.modifyClientToken.clientID', index=0,
      number=1, type=4, cpp_type=4, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='tokenName', full_name='CMD.modifyClientToken.tokenName', index=1,
      number=2, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='amount', full_name='CMD.modifyClientToken.amount', index=2,
      number=3, type=2, cpp_type=6, label=1,
      has_default_value=False, default_value=float(0),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='timestamp', full_name='CMD.modifyClientToken.timestamp', index=3,
      number=4, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='transactionID', full_name='CMD.modifyClientToken.transactionID', index=4,
      number=5, type=4, cpp_type=4, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=189,
  serialized_end=303,
)


_CHECKBALANCE = _descriptor.Descriptor(
  name='checkBalance',
  full_name='CMD.checkBalance',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='clientID', full_name='CMD.checkBalance.clientID', index=0,
      number=1, type=4, cpp_type=4, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='tokenName', full_name='CMD.checkBalance.tokenName', index=1,
      number=2, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=305,
  serialized_end=356,
)


_CHECKALLOWANCE = _descriptor.Descriptor(
  name='checkAllowance',
  full_name='CMD.checkAllowance',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='clientID', full_name='CMD.checkAllowance.clientID', index=0,
      number=1, type=4, cpp_type=4, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='tokenName', full_name='CMD.checkAllowance.tokenName', index=1,
      number=2, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='amount', full_name='CMD.checkAllowance.amount', index=2,
      number=3, type=2, cpp_type=6, label=1,
      has_default_value=False, default_value=float(0),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=358,
  serialized_end=427,
)


_MAKEREQUEST = _descriptor.Descriptor(
  name='makeRequest',
  full_name='CMD.makeRequest',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='clientID', full_name='CMD.makeRequest.clientID', index=0,
      number=1, type=4, cpp_type=4, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='tokenName', full_name='CMD.makeRequest.tokenName', index=1,
      number=2, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='amount', full_name='CMD.makeRequest.amount', index=2,
      number=3, type=2, cpp_type=6, label=1,
      has_default_value=False, default_value=float(0),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='timestamp', full_name='CMD.makeRequest.timestamp', index=3,
      number=4, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='requestID', full_name='CMD.makeRequest.requestID', index=4,
      number=5, type=4, cpp_type=4, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='sessionID', full_name='CMD.makeRequest.sessionID', index=5,
      number=6, type=4, cpp_type=4, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=429,
  serialized_end=552,
)


_APPROVEREQUEST = _descriptor.Descriptor(
  name='approveRequest',
  full_name='CMD.approveRequest',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='requestID', full_name='CMD.approveRequest.requestID', index=0,
      number=1, type=4, cpp_type=4, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='approveStatus', full_name='CMD.approveRequest.approveStatus', index=1,
      number=2, type=8, cpp_type=7, label=1,
      has_default_value=False, default_value=False,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='tokenName', full_name='CMD.approveRequest.tokenName', index=2,
      number=3, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='timestamp', full_name='CMD.approveRequest.timestamp', index=3,
      number=4, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='transactionID', full_name='CMD.approveRequest.transactionID', index=4,
      number=5, type=4, cpp_type=4, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='sessionID', full_name='CMD.approveRequest.sessionID', index=5,
      number=6, type=4, cpp_type=4, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=555,
  serialized_end=693,
)


_TRANSFER = _descriptor.Descriptor(
  name='transfer',
  full_name='CMD.transfer',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='clientID', full_name='CMD.transfer.clientID', index=0,
      number=1, type=4, cpp_type=4, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='tokenName', full_name='CMD.transfer.tokenName', index=1,
      number=2, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='amount', full_name='CMD.transfer.amount', index=2,
      number=3, type=2, cpp_type=6, label=1,
      has_default_value=False, default_value=float(0),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='timestamp', full_name='CMD.transfer.timestamp', index=3,
      number=4, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='transactionID', full_name='CMD.transfer.transactionID', index=4,
      number=5, type=4, cpp_type=4, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=695,
  serialized_end=800,
)

DESCRIPTOR.message_types_by_name['createToken'] = _CREATETOKEN
DESCRIPTOR.message_types_by_name['grantToken'] = _GRANTTOKEN
DESCRIPTOR.message_types_by_name['modifyClientToken'] = _MODIFYCLIENTTOKEN
DESCRIPTOR.message_types_by_name['checkBalance'] = _CHECKBALANCE
DESCRIPTOR.message_types_by_name['checkAllowance'] = _CHECKALLOWANCE
DESCRIPTOR.message_types_by_name['makeRequest'] = _MAKEREQUEST
DESCRIPTOR.message_types_by_name['approveRequest'] = _APPROVEREQUEST
DESCRIPTOR.message_types_by_name['transfer'] = _TRANSFER
_sym_db.RegisterFileDescriptor(DESCRIPTOR)

createToken = _reflection.GeneratedProtocolMessageType('createToken', (_message.Message,), dict(
  DESCRIPTOR = _CREATETOKEN,
  __module__ = 'tknCPD_pb2'
  # @@protoc_insertion_point(class_scope:CMD.createToken)
  ))
_sym_db.RegisterMessage(createToken)

grantToken = _reflection.GeneratedProtocolMessageType('grantToken', (_message.Message,), dict(
  DESCRIPTOR = _GRANTTOKEN,
  __module__ = 'tknCPD_pb2'
  # @@protoc_insertion_point(class_scope:CMD.grantToken)
  ))
_sym_db.RegisterMessage(grantToken)

modifyClientToken = _reflection.GeneratedProtocolMessageType('modifyClientToken', (_message.Message,), dict(
  DESCRIPTOR = _MODIFYCLIENTTOKEN,
  __module__ = 'tknCPD_pb2'
  # @@protoc_insertion_point(class_scope:CMD.modifyClientToken)
  ))
_sym_db.RegisterMessage(modifyClientToken)

checkBalance = _reflection.GeneratedProtocolMessageType('checkBalance', (_message.Message,), dict(
  DESCRIPTOR = _CHECKBALANCE,
  __module__ = 'tknCPD_pb2'
  # @@protoc_insertion_point(class_scope:CMD.checkBalance)
  ))
_sym_db.RegisterMessage(checkBalance)

checkAllowance = _reflection.GeneratedProtocolMessageType('checkAllowance', (_message.Message,), dict(
  DESCRIPTOR = _CHECKALLOWANCE,
  __module__ = 'tknCPD_pb2'
  # @@protoc_insertion_point(class_scope:CMD.checkAllowance)
  ))
_sym_db.RegisterMessage(checkAllowance)

makeRequest = _reflection.GeneratedProtocolMessageType('makeRequest', (_message.Message,), dict(
  DESCRIPTOR = _MAKEREQUEST,
  __module__ = 'tknCPD_pb2'
  # @@protoc_insertion_point(class_scope:CMD.makeRequest)
  ))
_sym_db.RegisterMessage(makeRequest)

approveRequest = _reflection.GeneratedProtocolMessageType('approveRequest', (_message.Message,), dict(
  DESCRIPTOR = _APPROVEREQUEST,
  __module__ = 'tknCPD_pb2'
  # @@protoc_insertion_point(class_scope:CMD.approveRequest)
  ))
_sym_db.RegisterMessage(approveRequest)

transfer = _reflection.GeneratedProtocolMessageType('transfer', (_message.Message,), dict(
  DESCRIPTOR = _TRANSFER,
  __module__ = 'tknCPD_pb2'
  # @@protoc_insertion_point(class_scope:CMD.transfer)
  ))
_sym_db.RegisterMessage(transfer)


# @@protoc_insertion_point(module_scope)
